import { Link } from 'react-router-dom';
import useLanguage from '../../context/useLanguage';
import { WAITLIST_TRANSITIONS } from '../../hooks/useWaitlist';

function formatDate(value, locale) {
  if (!value) return null;
  return new Intl.DateTimeFormat(locale, { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${value}T00:00:00`));
}

function statusLabel(status, t) { return t({ waiting: 'Waiting', contacted: 'Contacted', booked: 'Booked', removed: 'Removed' }[status] || status); }

export default function WaitlistQueue({ entries, isLoading, isSubmitting, onTransition }) {
  const { t, locale } = useLanguage();
  if (isLoading) return <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="h-40 animate-pulse rounded-2xl bg-slate-100" /></section>;
  return <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="border-b border-slate-200 pb-4"><h2 className="text-lg font-semibold text-slate-950">{t('Waitlist queue')}</h2><p className="text-sm text-slate-600">{t('Prioritised requests and their current state.')}</p></div><div className="mt-5 space-y-3">{entries.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 px-6 py-10 text-center"><p className="text-sm font-medium text-slate-800">{t('No waitlist entries found')}</p><p className="mt-2 text-sm text-slate-600">{t('There are no entries for this filter.')}</p></div> : entries.map((entry) => <div key={entry.id} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div className="min-w-0"><Link to={`/patients/${entry.patientId}`} className="text-base font-semibold text-teal-800 hover:text-teal-950">{entry.patient?.fullName || t('Unknown patient')}</Link><p className="mt-1 text-sm text-slate-700">{entry.reason}</p><p className="mt-2 text-xs font-medium text-slate-600">{entry.requestedDate ? `${t('Requested date')}: ${formatDate(entry.requestedDate, locale)}` : t('No requested date')}{entry.doctor?.name ? ` · ${entry.doctor.name}` : ''}{entry.notes ? ` · ${entry.notes}` : ''}</p></div><div className="flex items-center gap-3"><span className={`rounded-full px-3 py-1 text-xs font-semibold ring-1 ring-inset ${entry.priority === 'urgent' ? 'bg-amber-100 text-amber-900 ring-amber-300' : 'bg-white text-slate-700 ring-slate-300'}`}>{entry.priority === 'urgent' ? t('Urgent') : t('Normal')}</span><span className="rounded-full bg-white px-3 py-1 text-xs font-semibold text-slate-700 ring-1 ring-inset ring-slate-300">{statusLabel(entry.status, t)}</span>{WAITLIST_TRANSITIONS[entry.status]?.length > 0 ? <select data-testid={`waitlist-status-${entry.id}`} aria-label={`${t('Update waitlist entry')} ${entry.patient?.fullName || ''}`} disabled={isSubmitting} defaultValue="" onChange={(event) => { if (event.target.value) onTransition(entry.id, event.target.value); }} className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-xs font-medium text-slate-800"><option value="">{t('Update')}</option>{WAITLIST_TRANSITIONS[entry.status].map((nextStatus) => <option key={nextStatus} value={nextStatus}>{statusLabel(nextStatus, t)}</option>)}</select> : null}</div></div></div>)}</div></section>;
}
