import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { apiRequest } from '../services/api';
import useAuth from './useAuth';
import { LanguageContext } from './language-context';
import { LANGUAGE_OPTIONS } from './languageConstants';

const STORAGE_KEY = 'dentalpro-language';
const DEFAULT_LANGUAGE = 'en';

const translations = {
  'pt-PT': {
    'Clinic workspace': 'Espaço da clínica',
    'Main navigation': 'Navegação principal',
    'Skip to main content': 'Saltar para o conteúdo principal',
    'Clinical Suite': 'Suite clínica',
    Dashboard: 'Painel',
    Patients: 'Pacientes',
    patient: 'paciente',
    patients: 'pacientes',
    shown: 'apresentados',
    Agenda: 'Agenda',
    Doctors: 'Médicos',
    Settings: 'Definições',
    'Settings areas': 'Áreas das definições',
    Clinic: 'Clínica',
    Scheduling: 'Agendamento',
    Team: 'Equipa',
    Account: 'Conta',
    'Sign out': 'Terminar sessão',
    'Sign in': 'Iniciar sessão',
    'Signing in…': 'A iniciar sessão…',
    'Sign in to manage the clinic safely.': 'Inicie sessão para gerir a clínica em segurança.',
    Email: 'Email',
    Phone: 'Telefone',
    Specialty: 'Especialidade',
    Created: 'Criado em',
    NIF: 'NIF',
    Nationality: 'Nacionalidade',
    'No email': 'Sem email',
    Password: 'Palavra-passe',
    User: 'Utilizador',
    'Select user': 'Selecione o utilizador',
    'Choose your account': 'Escolha a sua conta',
    'Select your account': 'Selecione a sua conta',
    'Choose the account for this session': 'Escolha a conta para esta sessão',
    'Select your account before signing in.': 'Selecione a sua conta antes de iniciar sessão.',
    'No active users available.': 'Não existem utilizadores ativos disponíveis.',
    'Unable to load users': 'Não foi possível carregar os utilizadores',
    'Loading clinic workspace…': 'A carregar o espaço da clínica…',
    'Clinic setup': 'Configuração da clínica',
    'Configure the operational rules used by the agenda, new appointments, and rescheduling.': 'Configure as regras operacionais usadas pela agenda, pelos novos agendamentos e pelos reagendamentos.',
    'Only administrators can change clinic settings.': 'Apenas os administradores podem alterar as definições da clínica.',
    'Practice schedule': 'Horário da clínica',
    'These hours control every available start time in the booking engine.': 'Este horário controla todas as horas de início disponíveis no sistema de agendamento.',
    'Clinic name': 'Nome da clínica',
    'Edit clinic settings': 'Editar definições da clínica',
    'Edit closures': 'Editar encerramentos',
    'Edit appointment types': 'Editar tipos de consulta',
    'Weekly hours': 'Horário semanal',
    Timezone: 'Fuso horário',
    Language: 'Idioma',
    English: 'Inglês',
    'Portuguese (Portugal)': 'Português (Portugal)',
    Day: 'Dia',
    Open: 'Aberto',
    Closed: 'Encerrado',
    Hours: 'Horário',
    Break: 'Pausa',
    Monday: 'Segunda-feira',
    Tuesday: 'Terça-feira',
    Wednesday: 'Quarta-feira',
    Thursday: 'Quinta-feira',
    Friday: 'Sexta-feira',
    Saturday: 'Sábado',
    Sunday: 'Domingo',
    to: 'a',
    'Appointment grid is fixed at 30 minutes. The latest valid start is calculated from the closing time and duration.': 'A grelha de agendamento está fixa em intervalos de 30 minutos. A última hora válida é calculada a partir do fecho e da duração.',
    'Save schedule': 'Guardar horário',
    'Closures and holidays': 'Encerramentos e feriados',
    'Block a specific date without changing the weekly schedule.': 'Bloqueie uma data específica sem alterar o horário semanal.',
    'Reason, e.g. Christmas': 'Motivo, por exemplo Natal',
    Add: 'Adicionar',
    'No special closures configured.': 'Não existem encerramentos especiais configurados.',
    'Appointment types': 'Tipos de consulta',
    'Templates set the default duration used by new bookings.': 'Os modelos definem a duração predefinida dos novos agendamentos.',
    'Appointment type': 'Tipo de consulta',
    'Appointment type added.': 'Tipo de consulta adicionado.',
    'Appointment type saved.': 'Tipo de consulta guardado.',
    'Appointment type archived. Existing appointments are unchanged.': 'Tipo de consulta arquivado. As consultas existentes não foram alteradas.',
    'Provider availability': 'Disponibilidade dos médicos',
    'Override the clinic schedule for individual doctors when their working days differ.': 'Sobreponha o horário da clínica para médicos individuais quando os seus dias de trabalho forem diferentes.',
    Works: 'Trabalha',
    min: 'min',
    Remove: 'Remover',
    Archive: 'Arquivar',
    'works on': 'trabalha à',
    'Save provider schedule for': 'Guardar horário de',
    'Configure weekly availability': 'Configurar disponibilidade semanal',
    'Edit provider schedule': 'Editar horário do médico',
    'Signed-in account': 'Conta com sessão iniciada',
    'Edit account': 'Editar conta',
    'Password changes are available when you choose to edit this section.': 'A alteração da palavra-passe fica disponível ao editar esta secção.',
    'Settings are protected by role': 'As definições estão protegidas por função',
    'Slot interval: 30 minutes': 'Intervalo: 30 minutos',
    'Clinic schedule saved. Availability now uses these hours.': 'Horário da clínica guardado. A disponibilidade usa agora este horário.',
    'Closure added. No appointments can be booked on that date.': 'Encerramento adicionado. Não é possível marcar consultas nessa data.',
    'Closure removed.': 'Encerramento removido.',
    'Provider schedule saved.': 'Horário do médico guardado.',
    'Add a doctor first to configure provider availability.': 'Adicione primeiro um médico para configurar a disponibilidade.',
    'Failed to load clinic settings': 'Não foi possível carregar as definições da clínica',
    'Failed to save clinic settings': 'Não foi possível guardar as definições da clínica',
    'New password and confirmation do not match.': 'A nova palavra-passe e a confirmação não coincidem.',
    'Password changed successfully. Other signed-in sessions were signed out.': 'Palavra-passe alterada com sucesso. As outras sessões iniciadas foram terminadas.',
    'Failed to change password': 'Não foi possível alterar a palavra-passe',
    'Failed to add closure': 'Não foi possível adicionar o encerramento',
    'Failed to remove closure': 'Não foi possível remover o encerramento',
    'Failed to add appointment type': 'Não foi possível adicionar o tipo de consulta',
    'Failed to save appointment type': 'Não foi possível guardar o tipo de consulta',
    'Failed to archive appointment type': 'Não foi possível arquivar o tipo de consulta',
    'Failed to save provider schedule': 'Não foi possível guardar o horário do médico',
    'Current password': 'Palavra-passe atual',
    'New password': 'Nova palavra-passe',
    'Confirm new password': 'Confirmar nova palavra-passe',
    'Changing password…': 'A alterar a palavra-passe…',
    'Change password': 'Alterar palavra-passe',
    'Other sessions are revoked after a change': 'As outras sessões são terminadas após a alteração',
    'Loading clinic settings…': 'A carregar as definições da clínica…',
    'Save': 'Guardar',
    'Cancel': 'Cancelar',
    'Close': 'Fechar',
    'Search': 'Pesquisar',
    'Save changes': 'Guardar alterações',
    'No appointments': 'Sem consultas',
    'Upcoming agenda': 'Próximas consultas',
    'Clinic overview': 'Visão geral da clínica',
    'Review patients and upcoming appointments across the clinic.': 'Consulte os pacientes e as próximas consultas da clínica.',
    'Open Patients': 'Abrir pacientes',
    'Patient count': 'Número de pacientes',
    'Current registered patients': 'Pacientes atualmente registados',
    'Next scheduled appointments': 'Próximas consultas marcadas',
    'Unknown patient': 'Paciente desconhecido',
    Consultation: 'Consulta',
    'No upcoming appointments': 'Sem próximas consultas',
    'Future scheduled appointments will appear here.': 'As consultas futuras marcadas aparecerão aqui.',
    'Open agenda': 'Abrir agenda',
    'Add appointment': 'Adicionar consulta',
    'Add doctor': 'Adicionar médico',
    'Add patient': 'Adicionar paciente',
    'New patient': 'Novo paciente',
    'Add Patient': 'Adicionar paciente',
    'Create Patient': 'Criar paciente',
    'Appointment': 'Consulta',
    'Patient': 'Paciente',
    'Update staff record': 'Atualizar registo do profissional',
    'New doctor': 'Novo médico',
    'Edit Doctor': 'Editar médico',
    'Add Doctor': 'Adicionar médico',
    'Create Doctor': 'Criar médico',
    'Unable to load doctor': 'Não foi possível carregar o médico',
    'Failed to load doctor': 'Não foi possível carregar o médico',
    'Unable to load appointment': 'Não foi possível carregar a consulta',
    'Invalid appointment id': 'Identificador de consulta inválido',
    'Failed to load appointment details': 'Não foi possível carregar os detalhes da consulta',
    'Back to Agenda': 'Voltar à agenda',
    'Back to Doctors': 'Voltar aos médicos',
    'Doctor detail': 'Detalhes do médico',
    'Review doctor contact and professional information.': 'Consulte os dados de contacto e profissionais do médico.',
    'Doctor information': 'Informação do médico',
    'Basic details for this doctor record.': 'Dados básicos deste registo médico.',
    'No email recorded': 'Sem email registado',
    'No phone recorded': 'Sem telefone registado',
    'No NIF recorded': 'Sem NIF registado',
    'Unable to load dashboard': 'Não foi possível carregar o painel',
    'Failed to load dashboard': 'Não foi possível carregar o painel',
    'Failed to load patients': 'Não foi possível carregar os pacientes',
    'Failed to load appointments': 'Não foi possível carregar as consultas',
    'Failed to load agenda data': 'Não foi possível carregar os dados da agenda',
    'Failed to load patient workflow data': 'Não foi possível carregar os dados dos pacientes',
    'Failed to create patient': 'Não foi possível criar o paciente',
    'Unable to sign in': 'Não foi possível iniciar sessão',
    'Failed to load doctors': 'Não foi possível carregar os médicos',
    'Failed to load patient details': 'Não foi possível carregar os detalhes do paciente',
    'Search all patients and work from today\'s active appointment list.': 'Pesquise pacientes e trabalhe a partir da lista de consultas ativas de hoje.',
    'Search all patients by name, phone, email or NIF': 'Pesquisar pacientes por nome, telefone, email ou NIF',
    'Patient views': 'Vistas de pacientes',
    'Patients today': 'Pacientes de hoje',
    'Search patients': 'Pesquisar pacientes',
    'Search by patient details': 'Pesquisar pelos dados do paciente',
    'Enter a name, phone, email or NIF to find a patient.': 'Introduza um nome, telefone, email ou NIF para encontrar um paciente.',
    'Search by name, phone, email or nationality': 'Pesquisar por nome, telefone, email ou nacionalidade',
    'Try a different search term from the current list.': 'Tente outro termo de pesquisa na lista atual.',
    'Search results': 'Resultados da pesquisa',
    'All existing patients': 'Todos os pacientes existentes',
    result: 'resultado',
    results: 'resultados',
    'No matching patients found': 'Não foram encontrados pacientes correspondentes',
    'Try a different name, phone, email or NIF.': 'Tente outro nome, telefone, email ou NIF.',
    'Open patient': 'Abrir paciente',
    'Open doctor': 'Abrir médico',
    'Review staff records and open a doctor profile.': 'Consulte os registos da equipa e abra o perfil de um médico.',
    'Validate and close': 'Validar e fechar',
    'Awaiting doctor validation': 'A aguardar validação da doutora',
    'Patients with appointments today': 'Pacientes com consultas hoje',
    'No patients scheduled for today': 'Não há pacientes marcados para hoje',
    'Today\'s operational patient list will appear here once appointments exist.': 'A lista operacional de pacientes de hoje aparecerá aqui quando existirem consultas.',
    'Full name, phone, email, NIF and nationality are required': 'Nome completo, telefone, email, NIF e nacionalidade são obrigatórios',
    'Portuguese NIF must contain exactly 9 digits': 'O NIF português deve conter exatamente 9 algarismos',
    'Search all doctors and manage clinical staff records.': 'Pesquise médicos e faça a gestão dos registos da equipa clínica.',
    'Search all doctors by name, email, phone or specialty': 'Pesquisar médicos por nome, email, telefone ou especialidade',
    'No matching doctors found': 'Não foram encontrados médicos correspondentes',
    'Try a different name, specialty, email or phone number.': 'Tente outro nome, especialidade, email ou número de telefone.',
    'No specialty added.': 'Sem especialidade adicionada.',
    Delete: 'Eliminar',
    'Secretary workflow': 'Fluxo de trabalho da receção',
    'Review the week, prepare today\'s patients, and manage bookings.': 'Consulte a semana, prepare os pacientes de hoje e faça a gestão das marcações.',
    Week: 'Semana',
    Month: 'Mês',
    Today: 'Hoje',
    'Select a day or open an appointment.': 'Selecione um dia ou abra uma consulta.',
    'Single click selects a day. Use Open week to open the week view.': 'Um clique seleciona um dia. Use Abrir semana para abrir a vista semanal.',
    Select: 'Selecionar',
    'Open week': 'Abrir semana',
    more: 'mais',
    Mon: 'Seg',
    Tue: 'Ter',
    Wed: 'Qua',
    Thu: 'Qui',
    Fri: 'Sex',
    Sat: 'Sáb',
    Sun: 'Dom',
    appointment: 'consulta',
    appointments: 'consultas',
    'Add for this day': 'Adicionar neste dia',
    'No appointments for this day': 'Sem consultas para este dia',
    'Add a booking for this date to prepare the day ahead.': 'Adicione uma marcação para esta data para preparar o dia.',
    'Create Appointment': 'Criar consulta',
    'Update Appointment': 'Atualizar consulta',
    'Reschedule booking': 'Reagendar consulta',
    'New booking': 'Nova marcação',
    'Reschedule Appointment': 'Reagendar consulta',
    'Save reschedule': 'Guardar reagendamento',
    'Open appointment': 'Abrir consulta',
    'Close modal': 'Fechar janela',
    'Search by name or phone': 'Pesquisar por nome ou telefone',
    Recommended: 'Recomendados',
    'All patients': 'Todos os pacientes',
    'No patients found': 'Não foram encontrados pacientes',
    'Search by doctor name, email or phone': 'Pesquisar por nome, email ou telefone do médico',
    'No doctors found': 'Não foram encontrados médicos',
    'Appointment date': 'Data da consulta',
    'Selected date': 'Data selecionada',
    'Hide calendar': 'Ocultar calendário',
    'Choose date': 'Escolher data',
    Selected: 'Selecionada',
    Free: 'Livre',
    Unavailable: 'Indisponível',
    Existing: 'Existente',
    'Select doctor': 'Selecione um médico',
    'Select an option': 'Selecione uma opção',
    'Availability shown from 08:00 to 19:30 for the selected doctor, date and duration.': 'A disponibilidade apresentada é das 08:00 às 19:30 para o médico, data e duração selecionados.',
    'Select a doctor to see which 30-minute slots are free or booked.': 'Selecione um médico para ver quais os intervalos de 30 minutos estão livres ou marcados.',
    'Clinic closed on the selected date': 'A clínica está encerrada na data selecionada',
    'Failed to load doctor availability': 'Não foi possível carregar a disponibilidade do médico',
    'Patient, doctor, date, time and an active appointment type are required': 'O paciente, médico, data, hora e um tipo de consulta ativo são obrigatórios',
    'Failed to save appointment': 'Não foi possível guardar a consulta',
    Notes: 'Notas',
    Treatment: 'Tratamento',
    'No notes added.': 'Sem notas adicionadas.',
    'Save Changes': 'Guardar alterações',
    'No active appointment types configured': 'Não existem tipos de consulta ativos configurados',
    'Back to patients': 'Voltar aos pacientes',
    'Completed appointment': 'Consulta concluída',
    'Appointment detail': 'Detalhes da consulta',
    'Appointment information': 'Informação da consulta',
    'Completion record': 'Registo de conclusão',
    'Final outcome and clinical notes for this completed visit.': 'Resultado final e notas clínicas desta visita concluída.',
    'Scheduling and follow-up use the same validated booking flow.': 'O agendamento e o seguimento usam o mesmo fluxo validado.',
    'Performed treatment': 'Tratamento realizado',
    'Not recorded yet': 'Ainda não registado',
    'Completion note': 'Nota de conclusão',
    'No completion note recorded.': 'Não foi registada nota de conclusão.',
    minutes: 'minutos',
    'Scheduled treatment': 'Tratamento agendado',
    'Not recorded': 'Não registado',
    'No doctor assigned': 'Sem médico atribuído',
    'Scheduling notes': 'Notas de agendamento',
    'No scheduling notes recorded.': 'Não foram registadas notas de agendamento.',
    'Update the patient, doctor, treatment, or notes here. Use Reschedule to change the appointment date, time, or duration.': 'Atualize aqui o paciente, o médico, o tratamento ou as notas. Use Reagendar para alterar a data, hora ou duração da consulta.',
    'Select a patient': 'Selecionar um paciente',
    'Select a doctor': 'Selecionar um médico',
    'Doctor workflow': 'Fluxo de trabalho do médico',
    'Complete Appointment': 'Concluir consulta',
    'Record what was done, mark the appointment completed, and optionally continue to follow-up scheduling.': 'Registe o que foi feito, marque a consulta como concluída e, se necessário, avance para o agendamento de seguimento.',
    'Add a short completion note if needed': 'Adicione uma nota breve de conclusão, se necessário',
    'After conclusion': 'Após a conclusão',
    'Finish only': 'Concluir apenas',
    'Mark the appointment completed and stay on this page.': 'Marcar a consulta como concluída e permanecer nesta página.',
    'Finish and continue to reschedule': 'Concluir e continuar para reagendar',
    'After conclusion, open the booking form immediately so a follow-up slot can be assigned.': 'Após a conclusão, abrir imediatamente o formulário de marcação para atribuir um horário de seguimento.',
    'Delete action': 'Ação de eliminação',
    'Deleting...': 'A eliminar…',
    'Confirm doctor deletion': 'Confirmar eliminação do médico',
    'Confirm patient deletion': 'Confirmar eliminação do paciente',
    'Are you sure you want to delete patient': 'Tem a certeza de que pretende eliminar o paciente',
    Back: 'Voltar',
    Edit: 'Editar',
    'Patient file': 'Processo do paciente',
    'Operational patient details and appointment history.': 'Dados operacionais e histórico de consultas do paciente.',
    'Patient not found': 'Paciente não encontrado',
    'The requested patient record could not be loaded.': 'Não foi possível carregar o processo do paciente solicitado.',
    'Upcoming appointments': 'Próximas consultas',
    'Current and future appointments for this patient.': 'Consultas atuais e futuras deste paciente.',
    'This patient does not have any upcoming bookings yet.': 'Este paciente ainda não tem marcações futuras.',
    'Recent completed appointments': 'Consultas concluídas recentes',
    'Latest completed work already recorded for this patient.': 'Trabalho concluído mais recente já registado para este paciente.',
    'No completed appointments yet': 'Ainda não existem consultas concluídas',
    'Completed treatment history will appear here once appointments are concluded.': 'O histórico de tratamentos concluídos aparecerá aqui quando as consultas forem concluídas.',
    'Open section': 'Abrir secção',
    'Close section': 'Fechar secção',
    'Patient areas': 'Áreas do paciente',
    Overview: 'Resumo',
    Operations: 'Operações',
    'Compliance checklist': 'Checklist de conformidade',
    'The app separates automatic technical signals from evidence and approval that must be completed by the clinic. This is an operational control, not legal certification.': 'A aplicação separa os sinais técnicos automáticos da evidência e aprovação que têm de ser concluídas pela clínica. Este é um controlo operacional, não uma certificação legal.',
    'Select a checklist item to see the suggested procedure and evidence.': 'Selecione um item do checklist para consultar o procedimento e a evidência sugeridos.',
    Refresh: 'Atualizar',
    Automatic: 'Automático',
    'Approved by': 'Aprovado por',
    'Evidence / approval': 'Evidência / aprovação',
    'Manual state': 'Estado manual',
    Approved: 'Aprovado',
    'Automatic check passed': 'Verificação automática concluída',
    'Pending review': 'Pendente de revisão',
    'Needs correction': 'Necessita de correção',
    'Not applicable': 'Não aplicável',
    'Needs operational review': 'Necessita de revisão operacional',
    'Manual evidence required': 'Evidência manual necessária',
    'Not checked': 'Não verificado',
    'Clinic and legal': 'Clínica e legal',
    'Privacy and records': 'Privacidade e registos',
    Security: 'Segurança',
    Continuity: 'Continuidade',
    'Clinical workflow': 'Fluxo clínico',
    Governance: 'Governação',
    'Evidence reference': 'Referência da evidência',
    'Document name, location, date, or signed record': 'Nome do documento, localização, data ou registo assinado',
    'Approved by me': 'Aprovado por mim',
    'Suggested procedure': 'Procedimento sugerido',
    'Suggested evidence': 'Evidência sugerida',
    'Suggested responsible': 'Responsável sugerido',
    'Create one verified clinic identity record and keep its registration evidence together.': 'Crie um registo validado da identidade da clínica e mantenha junta a evidência do respetivo registo.',
    'Confirm the legal name, address, NIPC/NIF, contacts, and ERS registration details.': 'Confirme a denominação legal, morada, NIPC/NIF, contactos e dados do registo na ERS.',
    'Add the applicable licence or registration references and check that they are current.': 'Adicione as referências das licenças ou registos aplicáveis e confirme que estão atualizados.',
    'Store the signed or official source reference in the evidence field and set the responsible person.': 'Guarde no campo da evidência a referência da fonte oficial ou assinada e indique o responsável.',
    'Clinic information sheet, ERS registration proof, applicable licences, and date of last review.': 'Ficha de identificação da clínica, comprovativo do registo na ERS, licenças aplicáveis e data da última revisão.',
    'Clinic administrator, with clinical lead confirmation where the information affects clinical operation.': 'Responsável da clínica, com confirmação da responsável clínica quando a informação afete a operação clínica.',
    'Document who is responsible for data protection, privacy coordination, and clinical leadership.': 'Documente quem é responsável pela proteção de dados, coordenação da privacidade e liderança clínica.',
    'Name the person responsible for processing personal data and the privacy contact for requests.': 'Identifique a pessoa responsável pelo tratamento de dados pessoais e o contacto de privacidade para pedidos.',
    'Record the clinical lead and define who can approve clinical and operational decisions.': 'Registe a responsável clínica e defina quem pode aprovar decisões clínicas e operacionais.',
    'Review the names and contact channels whenever the clinic team changes.': 'Reveja os nomes e canais de contacto sempre que a equipa da clínica mudar.',
    'Signed responsibility matrix, internal appointment record, or approved clinic policy.': 'Matriz de responsabilidades assinada, nomeação interna ou política da clínica aprovada.',
    'Clinic administrator and clinical lead.': 'Responsável da clínica e responsável clínica.',
    'Make sure patients receive the approved privacy information through a traceable channel.': 'Assegure que os pacientes recebem a informação de privacidade aprovada através de um canal rastreável.',
    'Use the clinic-approved privacy notice and verify that its contact details are current.': 'Utilize a informação de privacidade aprovada pela clínica e confirme que os contactos estão atualizados.',
    'Decide when and how it is delivered to patients, including the paper workflow.': 'Defina quando e como é entregue aos pacientes, incluindo o fluxo em papel.',
    'Record the version, approval date, delivery channel, and where the final document is stored.': 'Registe a versão, data de aprovação, canal de entrega e local onde o documento final é guardado.',
    'Approved privacy notice, version/date, delivery procedure, and sample patient-facing channel.': 'Informação de privacidade aprovada, versão/data, procedimento de entrega e exemplo do canal disponibilizado ao paciente.',
    'Privacy/data protection responsible person.': 'Responsável pela privacidade/proteção de dados.',
    'Keep a current register of the clinic’s personal-data processing activities.': 'Mantenha atualizado o registo das atividades de tratamento de dados pessoais da clínica.',
    'List the purposes, patient and staff data categories, recipients, systems, and access roles.': 'Enumere as finalidades, categorias de dados de pacientes e equipa, destinatários, sistemas e perfis de acesso.',
    'Document retention periods, security measures, and any transfers or external processors.': 'Documente os prazos de conservação, medidas de segurança e eventuais transferências ou subcontratantes.',
    'Review the register after a new feature, supplier, workflow, or data category is introduced.': 'Reveja o registo após introduzir uma funcionalidade, fornecedor, fluxo ou categoria de dados novos.',
    'Approved processing register with owner, review date, and linked supplier or system records.': 'Registo de atividades aprovado, com responsável, data de revisão e referências aos fornecedores ou sistemas relacionados.',
    'Privacy/data protection responsible person, supported by the technical administrator.': 'Responsável pela privacidade/proteção de dados, com apoio do administrador técnico.',
    'Agree and document how long each relevant record is kept and what happens afterwards.': 'Acorde e documente durante quanto tempo cada registo relevante é conservado e o que acontece depois.',
    'List the record types used by the clinic, including clinical records, documents, audit logs, and requests.': 'Liste os tipos de registos usados pela clínica, incluindo processos clínicos, documentos, auditorias e pedidos.',
    'Obtain the clinic’s legal and clinical decision for each retention period and exception.': 'Obtenha a decisão jurídica e clínica da clínica para cada prazo de conservação e exceção.',
    'Record review dates, legal holds, and the approved deletion or anonymisation procedure.': 'Registe datas de revisão, bloqueios legais e o procedimento aprovado de eliminação ou anonimização.',
    'Approved retention schedule, decision record, and documented exceptions or holds.': 'Tabela de conservação aprovada, registo da decisão e exceções ou bloqueios documentados.',
    'Clinic administrator with clinical and legal/privacy input.': 'Responsável da clínica, com contributos clínicos e jurídico/privacidade.',
    'Ensure every user has only the access needed for their daily responsibility.': 'Garanta que cada utilizador tem apenas o acesso necessário à sua responsabilidade diária.',
    'Review the secretary, clinical lead, and technical administrator permissions separately.': 'Reveja separadamente as permissões da secretária, responsável clínica e administrador técnico.',
    'Confirm who may view, create, edit, validate, export, or delete each sensitive record type.': 'Confirme quem pode consultar, criar, editar, validar, exportar ou eliminar cada tipo de registo sensível.',
    'Remove unused accounts and repeat the review after role or staff changes.': 'Remova contas sem utilização e repita a revisão após alterações de funções ou equipa.',
    'Approved role-permission matrix, account review date, and list of exceptions.': 'Matriz de perfis e permissões aprovada, data da revisão das contas e lista de exceções.',
    'Clinic administrator, with clinical lead approval for clinical access.': 'Responsável da clínica, com aprovação da responsável clínica para o acesso clínico.',
    'Protect privileged and clinical-data accounts with multi-factor authentication.': 'Proteja as contas privilegiadas e com acesso a dados clínicos através de autenticação multifator.',
    'Enable MFA for administrators and any account with access to clinical data or exports.': 'Ative MFA para administradores e para qualquer conta com acesso a dados clínicos ou exportações.',
    'Test sign-in, recovery codes, account recovery, and session revocation for each privileged account.': 'Teste o início de sessão, códigos de recuperação, recuperação da conta e revogação de sessões de cada conta privilegiada.',
    'Record the completion date without storing MFA secrets or recovery codes in the app.': 'Registe a data de conclusão sem guardar segredos MFA ou códigos de recuperação na aplicação.',
    'Account security review, test date, and list of accounts confirmed to use MFA.': 'Revisão de segurança das contas, data dos testes e lista das contas confirmadas com MFA.',
    'Technical administrator, verified by the clinic administrator.': 'Administrador técnico, verificado pelo responsável da clínica.',
    'Run the production application over HTTPS with secure session and origin settings.': 'Execute a aplicação de produção através de HTTPS, com sessões e origens configuradas de forma segura.',
    'Confirm the production certificate, HTTPS redirect, secure cookies, and allowed client origin.': 'Confirme o certificado de produção, redirecionamento HTTPS, cookies seguros e origem do cliente permitida.',
    'Test login, logout, session expiry, and the browser security indicators from the clinic network.': 'Teste o início e fim de sessão, expiração da sessão e indicadores de segurança do navegador a partir da rede da clínica.',
    'Document the proxy or hosting configuration and its renewal/monitoring owner.': 'Documente a configuração do proxy ou alojamento e o responsável pela renovação/monitorização.',
    'Production URL, certificate/renewal record, security configuration review, and test date.': 'URL de produção, registo do certificado/renovação, revisão da configuração de segurança e data do teste.',
    'Confirm that a local deployment is bound to the clinic computer only and is not exposed to the network.': 'Confirme que uma instalação local está limitada ao computador da clínica e não está exposta à rede.',
    'Set the backend and frontend to listen on 127.0.0.1 or localhost, not on all network interfaces.': 'Configure o backend e frontend para escutarem em 127.0.0.1 ou localhost, e não em todas as interfaces de rede.',
    'Check the operating-system firewall and router so the application ports are not reachable by other devices.': 'Verifique a firewall do sistema operativo e o router para garantir que as portas da aplicação não são acessíveis por outros dispositivos.',
    'If another device ever needs access, switch to a controlled HTTPS deployment and document its proxy and certificate owner.': 'Se algum dia for necessário acesso a partir de outro dispositivo, mude para uma instalação HTTPS controlada e documente o responsável pelo proxy e certificado.',
    'HOST/LOCAL_ONLY configuration, firewall review, local access test, and review date.': 'Configuração HOST/LOCAL_ONLY, revisão da firewall, teste de acesso local e data da revisão.',
    'Protect the database and private documents if the production host or disk is accessed offline.': 'Proteja a base de dados e os documentos privados caso o host ou disco de produção seja acedido offline.',
    'Identify the host, volumes, backups, and removable media that contain clinic data.': 'Identifique o host, volumes, cópias de segurança e suportes amovíveis que contêm dados da clínica.',
    'Enable BitLocker or equivalent full-volume encryption and store recovery procedures securely.': 'Ative o BitLocker ou cifragem equivalente de todo o volume e guarde em segurança os procedimentos de recuperação.',
    'Test restart/recovery and document who can operate it without exposing the encryption keys.': 'Teste o reinício/recuperação e documente quem pode operar o sistema sem expor as chaves de cifragem.',
    'Host encryption status, recovery procedure, scope of encrypted volumes, and verification date.': 'Estado da cifragem do host, procedimento de recuperação, volumes abrangidos e data de verificação.',
    'Technical administrator or hosting provider.': 'Administrador técnico ou fornecedor de alojamento.',
    'Keep uploaded documents outside the public web root with restricted access and traceability.': 'Mantenha os documentos carregados fora do web root público, com acesso restrito e rastreabilidade.',
    'Confirm the storage directory is private and cannot be opened through a guessed URL.': 'Confirme que a diretoria de armazenamento é privada e não pode ser aberta através de um URL adivinhado.',
    'Test download permissions for the secretary, clinical lead, and unauthorised user scenarios.': 'Teste as permissões de descarga nos cenários da secretária, responsável clínica e utilizador não autorizado.',
    'Confirm documents are included in encrypted backups and that access is audited.': 'Confirme que os documentos estão incluídos nas cópias cifradas e que os acessos são auditados.',
    'Storage path/configuration review, permission tests, backup inclusion, and review date.': 'Revisão do caminho/configuração, testes de permissões, inclusão nas cópias e data da revisão.',
    'Technical administrator, with clinic administrator verification.': 'Administrador técnico, com verificação do responsável da clínica.',
    'Create recent encrypted backups and keep a separate copy that can be used after an incident.': 'Crie cópias de segurança cifradas recentes e mantenha uma cópia separada utilizável após um incidente.',
    'Schedule database and document backups at an interval suitable for the clinic workflow.': 'Agende cópias da base de dados e documentos num intervalo adequado ao funcionamento da clínica.',
    'Verify encryption, completion status, retention, and the external/secondary copy.': 'Verifique a cifragem, estado de conclusão, conservação e cópia externa/secundária.',
    'Configure an alert or daily review so a failed backup is noticed promptly.': 'Configure um alerta ou revisão diária para que uma cópia falhada seja detetada rapidamente.',
    'Latest backup status, schedule, encryption confirmation, secondary location, and review owner.': 'Estado da última cópia, agendamento, confirmação da cifragem, localização secundária e responsável pela revisão.',
    'Prove that the clinic can restore its data and record how long the recovery takes.': 'Demonstre que a clínica consegue restaurar os seus dados e registe o tempo necessário para a recuperação.',
    'Choose a safe test environment and restore a recent backup without touching production data.': 'Escolha um ambiente de teste seguro e restaure uma cópia recente sem tocar nos dados de produção.',
    'Check users, appointments, patients, clinical records, documents, and audit history.': 'Verifique utilizadores, consultas, pacientes, registos clínicos, documentos e histórico de auditoria.',
    'Record the date, operator, RPO, RTO, result, and any corrective action.': 'Registe a data, operador, RPO, RTO, resultado e qualquer ação corretiva.',
    'Completed restore report with test environment, checks performed, timings, and result.': 'Relatório de restauro concluído, com ambiente de teste, verificações, tempos e resultado.',
    'Technical administrator, with clinic administrator sign-off.': 'Administrador técnico, com validação do responsável da clínica.',
    'Move paper records into the app while preserving a clear transcription and clinical validation trail.': 'Transfira os registos em papel para a aplicação mantendo um percurso claro de transcrição e validação clínica.',
    'Create the patient and transcribe only from the source paper record, keeping the transcription marked as draft.': 'Crie o paciente e transcreva apenas a partir do registo em papel, mantendo a transcrição marcada como rascunho.',
    'Record the source/date and flag uncertainties instead of silently guessing missing information.': 'Registe a fonte/data e assinale dúvidas em vez de adivinhar silenciosamente a informação em falta.',
    'Ask the doctor to review and mark the transcription as validated before treating it as final clinical data.': 'Peça à doutora para rever e marcar a transcrição como validada antes de a considerar dado clínico final.',
    'Migration batch/list, source reference, transcription status, validation date, and doctor approval.': 'Lote/lista de migração, referência da fonte, estado da transcrição, data de validação e aprovação da doutora.',
    'Secretary for transcription; clinical lead for validation.': 'Secretária para a transcrição; responsável clínica para a validação.',
    'Handle access, correction, or deletion requests consistently and with identity verification.': 'Trate de forma consistente os pedidos de acesso, correção ou eliminação, verificando a identidade.',
    'Define the intake channel and verify the requester’s identity before disclosing or changing data.': 'Defina o canal de receção e verifique a identidade do requerente antes de divulgar ou alterar dados.',
    'Register the request, scope, owner, due date, response, and any reason for restriction or refusal.': 'Registe o pedido, âmbito, responsável, prazo, resposta e qualquer motivo de limitação ou recusa.',
    'Use the application export/correction workflow and keep the final response and evidence together.': 'Utilize o fluxo de exportação/correção da aplicação e mantenha juntas a resposta final e a evidência.',
    'Approved procedure, request log example, identity-check method, and response template.': 'Procedimento aprovado, exemplo do registo de pedidos, método de verificação da identidade e modelo de resposta.',
    'Give the clinic a repeatable response when data, accounts, devices, or availability are compromised.': 'Dê à clínica uma resposta repetível quando dados, contas, dispositivos ou disponibilidade forem comprometidos.',
    'Define the reporting channel, first responder, containment steps, and escalation contacts.': 'Defina o canal de comunicação, primeiro responsável, passos de contenção e contactos de escalamento.',
    'Record what happened, when it was detected, affected data, actions taken, and decisions made.': 'Registe o que aconteceu, quando foi detetado, os dados afetados, ações tomadas e decisões.',
    'Run a short exercise and update the procedure after incidents or major system changes.': 'Faça um exercício curto e atualize o procedimento após incidentes ou alterações relevantes do sistema.',
    'Incident procedure, contact list, exercise record, and post-incident improvement log.': 'Procedimento de incidentes, lista de contactos, registo do exercício e melhorias pós-incidente.',
    'Clinic administrator with technical and clinical escalation contacts.': 'Responsável da clínica com contactos de escalamento técnico e clínico.',
    'Capture the clinic’s approval that the production setup and operating procedures are ready.': 'Registe a aprovação da clínica de que a configuração de produção e os procedimentos operacionais estão prontos.',
    'Review accounts, roles, MFA, HTTPS, private documents, backups, restore test, retention, and incident contacts.': 'Reveja contas, perfis, MFA, HTTPS, documentos privados, cópias, teste de restauro, conservação e contactos de incidentes.',
    'Record open risks and owners instead of approving an incomplete setup without qualification.': 'Registe os riscos em aberto e responsáveis em vez de aprovar sem ressalvas uma configuração incompleta.',
    'Sign/date the deployment decision and repeat it after material infrastructure or workflow changes.': 'Assine e date a decisão de deployment e repita-a após alterações materiais da infraestrutura ou do fluxo.',
    'Deployment checklist, open-risk register, approval record, approver, and date.': 'Checklist de deployment, registo de riscos em aberto, aprovação, aprovador e data.',
    'Clinic administrator and clinical lead, with technical administrator input.': 'Responsável da clínica e responsável clínica, com contributo do administrador técnico.',
    'Compliance record saved.': 'Registo de conformidade guardado.',
    'Unable to load compliance checklist': 'Não foi possível carregar o checklist de conformidade',
    'Unable to save compliance record': 'Não foi possível guardar o registo de conformidade',
    'Loading compliance checklist...': 'A carregar o checklist de conformidade…',
    'Review the completed visit outcome and recorded notes.': 'Consulte o resultado da visita e as notas registadas.',
    'Review timing, treatment, completion outcome, and reschedule safely when needed.': 'Consulte o horário, tratamento e resultado, e reagende em segurança quando necessário.',
    'Edit appointment': 'Editar consulta',
    Reschedule: 'Reagendar',
    'Patient information': 'Informação do paciente',
    'Full name': 'Nome completo',
    'Save patient': 'Guardar paciente',
    'Patient updated successfully.': 'Paciente atualizado com sucesso.',
    'Failed to update patient': 'Não foi possível atualizar o paciente',
    'Failed to archive patient': 'Não foi possível arquivar o paciente',
    'Linked patient information': 'Informação do paciente associado',
    'No phone number available': 'Número de telefone indisponível',
    'Open patient record': 'Abrir registo do paciente',
    'Related appointments': 'Consultas relacionadas',
    'Recent appointments for this patient': 'Consultas recentes deste paciente',
    'No other appointments found': 'Não foram encontradas outras consultas',
    'Mark as arrived': 'Marcar como chegado',
    'Mark as no-show': 'Marcar como falta',
    'Conclude appointment': 'Concluir consulta',
    'Workflow actions': 'Ações da consulta',
    'Appointment status': 'Estado da consulta',
    'Current status': 'Estado atual',
    'Record attendance here. Rescheduling and completion are available in the top actions.': 'Registe aqui a presença. O reagendamento e a conclusão estão disponíveis nas ações superiores.',
    'Cancel appointment': 'Cancelar consulta',
    'Cancel this appointment?': 'Cancelar esta consulta?',
    'This will close the booking and remove it from active agenda and upcoming views.': 'Esta ação encerra a marcação e remove-a da agenda ativa e das próximas consultas.',
    'Keep appointment': 'Manter consulta',
    'Cancel booking': 'Cancelar marcação',
    'Cancelling…': 'A cancelar…',
    'Patient and doctor are required': 'O paciente e o médico são obrigatórios',
    'Appointment updated successfully.': 'Consulta atualizada com sucesso.',
    'Failed to update appointment': 'Não foi possível atualizar a consulta',
    'Date and time are required': 'A data e a hora são obrigatórias',
    'Please choose a 30-minute time slot such as 09:00 or 09:30': 'Escolha um horário de 30 minutos, como 09:00 ou 09:30',
    'Appointment rescheduled successfully.': 'Consulta reagendada com sucesso.',
    'Failed to reschedule appointment': 'Não foi possível reagendar a consulta',
    'Appointment concluded successfully.': 'Consulta concluída com sucesso.',
    'Failed to conclude appointment': 'Não foi possível concluir a consulta',
    'Appointment status updated successfully.': 'Estado da consulta atualizado com sucesso.',
    'Failed to update appointment status': 'Não foi possível atualizar o estado da consulta',
    'Appointment cancelled successfully.': 'Consulta cancelada com sucesso.',
    'Update attendance, conclude the visit, or move directly into follow-up scheduling.': 'Atualize a presença, conclua a consulta ou avance diretamente para o reagendamento.',
    'Reschedule appointment': 'Reagendar consulta',
    'Scheduling workflow': 'Fluxo de agendamento',
    'Close reschedule modal': 'Fechar janela de reagendamento',
    'Inspected day schedule': 'Agenda do dia consultado',
    'Inspected day bookings': 'Consultas do dia consultado',
    'Appointment summary': 'Resumo da consulta',
    'Failed to load inspected day schedule': 'Não foi possível carregar a agenda do dia consultado',
    at: 'às',
    'Previous day': 'Dia anterior',
    'Next day': 'Dia seguinte',
    'Loading day...': 'A carregar o dia…',
    'No date selected': 'Nenhuma data selecionada',
    'Current booking context': 'Contexto da consulta atual',
    'Original booking': 'Marcação original',
    'Selected slot': 'Horário selecionado',
    'Selected range': 'Intervalo selecionado',
    'Selected for': 'Selecionado para',
    'Current': 'Atual',
    'Start time': 'Hora de início',
    'No time selected': 'Nenhuma hora selecionada',
    'No appointment starts are available on this date.': 'Não existem horas de início disponíveis nesta data.',
    'No bookings found for this inspected day.': 'Não foram encontradas marcações neste dia.',
    'Available to book': 'Disponível para marcação',
    'Booked / blocked': 'Marcado / bloqueado',
    'Free selectable': 'Livre e selecionável',
    'Unavailable for this duration': 'Indisponível para esta duração',
    'Conflicts with duration': 'Entra em conflito com a duração',
    'All valid timeline starts for the selected duration are currently open.': 'Todas as horas de início válidas para a duração selecionada estão disponíveis.',
    'Existing appointments already blocking this doctor on': 'Já existem consultas a bloquear este médico em',
    'Clinic closed': 'Clínica encerrada',
    'Ready to submit': 'Pronto para guardar',
    'What will be submitted': 'Dados a guardar',
    'Select slot': 'Selecionar horário',
    'Conclude Appointment': 'Concluir consulta',
    'This appointment has already been concluded.': 'Esta consulta já foi concluída.',
    'This appointment is closed and cannot be edited or rescheduled': 'Esta consulta está encerrada e não pode ser editada ou reagendada.',
    'Clinical record': 'Registo clínico',
    'Clinical workspace': 'Espaço clínico',
    'Record medical context, tooth-level findings, clinical notes and planned care in one patient file.': 'Registe o contexto médico, achados por dente, notas clínicas e cuidados planeados num único processo do paciente.',
    'Editable clinical workspace': 'Espaço clínico editável',
    'Read-only clinical workspace': 'Espaço clínico só de leitura',
    'Medical and dental context': 'Contexto médico e dentário',
    'Edit medical context': 'Editar contexto médico',
    'Edit odontogram': 'Editar odontograma',
    'Edit treatment plans': 'Editar planos de tratamento',
    'Add clinical note': 'Adicionar nota clínica',
    'Close editor': 'Fechar editor',
    'No findings recorded for this tooth.': 'Não existem achados registados neste dente.',
    'No clinical note': 'Sem nota clínica',
    'Select Edit odontogram to change findings.': 'Selecione “Editar odontograma” para alterar os achados.',
    Portuguese: 'Portuguesa',
    'Date of birth': 'Data de nascimento',
    'Keep important safety information visible before treatment.': 'Mantenha a informação de segurança importante visível antes do tratamento.',
    Allergies: 'Alergias',
    'Current medication': 'Medicação atual',
    'Medical conditions': 'Condições médicas',
    'Dental history and alerts': 'Histórico dentário e alertas',
    'Medication, latex or other allergies': 'Alergias a medicamentos, látex ou outras',
    'Medication and dosage': 'Medicação e dosagem',
    'Relevant conditions and precautions': 'Condições relevantes e precauções',
    'Previous dental history, anxieties or preferences': 'Histórico dentário, receios ou preferências',
    'Emergency contact': 'Contacto de emergência',
    'Emergency phone': 'Telefone de emergência',
    'Save clinical profile': 'Guardar perfil clínico',
    'Interactive odontogram': 'Odontograma interativo',
    'Selected tooth': 'Dente selecionado',
    'Select a tooth, choose a surface and record its current clinical finding.': 'Selecione um dente, escolha uma superfície e registe o achado clínico atual.',
    'Upper right': 'Superior direito',
    'Upper left': 'Superior esquerdo',
    'Lower left': 'Inferior esquerdo',
    'Lower right': 'Inferior direito',
    Tooth: 'Dente',
    Charted: 'Registado',
    Surface: 'Superfície',
    Condition: 'Condição',
    'Clinical note': 'Nota clínica',
    'Finding, material, or follow-up': 'Achado, material ou seguimento',
    'Save finding': 'Guardar achado',
    'Clinical notes': 'Notas clínicas',
    'Draft notes can be edited; finalized notes are locked for record integrity.': 'As notas de rascunho podem ser editadas; as notas finalizadas ficam bloqueadas para garantir a integridade do registo.',
    'Related appointment': 'Consulta associada',
    'No linked appointment': 'Sem consulta associada',
    'Chief complaint': 'Queixa principal',
    'Clinical findings': 'Achados clínicos',
    Diagnosis: 'Diagnóstico',
    'Treatment performed': 'Tratamento realizado',
    Recommendations: 'Recomendações',
    'Save draft note': 'Guardar nota de rascunho',
    'No clinical notes recorded yet.': 'Ainda não foram registadas notas clínicas.',
    'General clinical note': 'Nota clínica geral',
    Final: 'Final',
    Draft: 'Rascunho',
    Finalize: 'Finalizar',
    'Treatment plans': 'Planos de tratamento',
    'Organize recommended procedures and connect them to teeth before scheduling.': 'Organize os procedimentos recomendados e associe-os aos dentes antes do agendamento.',
    'New plan title': 'Título do novo plano',
    'e.g. Initial restorative plan': 'por exemplo, plano restaurador inicial',
    'Optional context': 'Contexto opcional',
    'Create plan': 'Criar plano',
    'No treatment plans created yet.': 'Ainda não foram criados planos de tratamento.',
    Procedure: 'Procedimento',
    'e.g. Composite restoration': 'por exemplo, restauração em compósito',
    'Tooth (optional)': 'Dente (opcional)',
    'Not specified': 'Não especificado',
    'Add procedure': 'Adicionar procedimento',
    'No procedures in this plan yet.': 'Ainda não existem procedimentos neste plano.',
    'Add at least one clinical note field before saving.': 'Preencha pelo menos um campo de nota clínica antes de guardar.',
    'Clinical profile saved.': 'Perfil clínico guardado.',
    'chart updated.': 'atualizado.',
    'finding removed.': 'achado removido.',
    'Clinical note saved as draft.': 'Nota clínica guardada como rascunho.',
    'Clinical note finalized and locked.': 'Nota clínica finalizada e bloqueada.',
    'Treatment plan title is required.': 'O título do plano de tratamento é obrigatório.',
    'Treatment plan created.': 'Plano de tratamento criado.',
    'Treatment plan status updated.': 'Estado do plano de tratamento atualizado.',
    'Select a plan and enter a procedure name.': 'Selecione um plano e introduza o nome de um procedimento.',
    'Treatment plan item added.': 'Procedimento adicionado ao plano.',
    'Unable to save clinical record': 'Não foi possível guardar o registo clínico',
    'Whole tooth': 'Dente completo',
    Mesial: 'Mesial',
    Distal: 'Distal',
    Occlusal: 'Oclusal',
    Incisal: 'Incisal',
    Buccal: 'Vestibular',
    Lingual: 'Lingual',
    Palatal: 'Palatina',
    Healthy: 'Saudável',
    Caries: 'Cárie',
    Restoration: 'Restauração',
    Missing: 'Ausente',
    Fracture: 'Fratura',
    Crown: 'Coroa',
    Implant: 'Implante',
    'Root canal': 'Tratamento endodôntico',
    'Extraction needed': 'Extração necessária',
    Other: 'Outro',
    'Active finding': 'Achado ativo',
    'Treatment planned': 'Tratamento planeado',
    Historical: 'Histórico',
    Accepted: 'Aceite',
    'In progress': 'Em curso',
    Declined: 'Recusado',
    Planned: 'Planeado',
    procedure: 'procedimento',
    procedures: 'procedimentos',
    'Medical history': 'Histórico clínico',
    'Treatment plan': 'Plano de tratamento',
    Odontogram: 'Odontograma',
    'Patient data governance': 'Governação dos dados do paciente',
    'Review consent history and export the structured patient record as JSON.': 'Consulte o histórico de consentimentos e exporte o registo estruturado do paciente em JSON.',
    'Preparing export...': 'A preparar a exportação…',
    'Download JSON export': 'Transferir exportação JSON',
    'Unable to load consent records.': 'Não foi possível carregar os registos de consentimento.',
    'Consent recorded.': 'Consentimento registado.',
    'Unable to record consent.': 'Não foi possível registar o consentimento.',
    'Withdraw this consent?': 'Retirar este consentimento?',
    'Consent withdrawn.': 'Consentimento retirado.',
    'Unable to withdraw consent.': 'Não foi possível retirar o consentimento.',
    'Structured patient record downloaded.': 'Registo estruturado do paciente transferido.',
    'Unable to export the patient record.': 'Não foi possível exportar o registo do paciente.',
    Purpose: 'Finalidade',
    'e.g. Treatment and care': 'por exemplo, Tratamento e cuidados',
    Version: 'Versão',
    'Signature reference': 'Referência da assinatura',
    optional: 'opcional',
    'Saving...': 'A guardar…',
    'Record consent': 'Registar consentimento',
    'Your role can view consent records and export this patient record, but cannot change consent.': 'A sua função pode consultar os registos de consentimento e exportar este registo do paciente, mas não pode alterar o consentimento.',
    'Consent history': 'Histórico de consentimentos',
    'Loading consent records...': 'A carregar os registos de consentimento…',
    'No consent records have been recorded.': 'Ainda não foram registados consentimentos.',
    Withdrawn: 'Retirado',
    Granted: 'Concedido',
    withdrawn: 'retirado',
    Withdraw: 'Retirar',
    'User management': 'Gestão de utilizadores',
    'Edit user management': 'Editar gestão de utilizadores',
    'Create staff accounts and control who can sign in to the clinic.': 'Crie contas da equipa e controle quem pode iniciar sessão na clínica.',
    'Failed to load users': 'Não foi possível carregar os utilizadores',
    'User created successfully.': 'Utilizador criado com sucesso.',
    'Failed to create user': 'Não foi possível criar o utilizador',
    'Failed to update user status': 'Não foi possível atualizar o estado do utilizador',
    'is now': 'está agora',
    Administrator: 'Administrador',
    Receptionist: 'Rececionista',
    Dentist: 'Médico dentista',
    'Display name': 'Nome a apresentar',
    Role: 'Função',
    'Temporary password': 'Palavra-passe temporária',
    'Saving…': 'A guardar…',
    'Create user': 'Criar utilizador',
    'Loading users…': 'A carregar utilizadores…',
    Name: 'Nome',
    Status: 'Estado',
    Action: 'Ação',
    '(you)': '(você)',
    Active: 'Ativo',
    Inactive: 'Inativo',
    'You cannot deactivate your own account': 'Não pode desativar a sua própria conta',
    'Cannot deactivate': 'Não é possível desativar',
    Deactivate: 'Desativar',
    Activate: 'Ativar',
    'No users found.': 'Não foram encontrados utilizadores.',
    'Your own active account cannot be deactivated here.': 'A sua própria conta ativa não pode ser desativada aqui.',
    Recalls: 'Seguimentos',
    'Patient follow-up': 'Seguimento de pacientes',
    'Recall queue': 'Fila de seguimentos',
    'Keep patient follow-ups visible and easy to update.': 'Mantenha os seguimentos dos pacientes visíveis e fáceis de atualizar.',
    'Follow-up dates and their current status.': 'Datas de seguimento e o respetivo estado.',
    'Record a date for the next patient follow-up.': 'Registe uma data para o próximo seguimento do paciente.',
    'Create recall': 'Criar seguimento',
    'Due date': 'Data prevista',
    Reason: 'Motivo',
    'e.g. Six-month check-up': 'por exemplo, consulta de rotina semestral',
    'Select patient': 'Selecionar paciente',
    'Patient, due date and reason are required.': 'Paciente, data prevista e motivo são obrigatórios.',
    'Filter by status': 'Filtrar por estado',
    Pending: 'Pendentes',
    Due: 'Pendente',
    Scheduled: 'Agendado',
    Completed: 'Concluído',
    Dismissed: 'Dispensado',
    'All statuses': 'Todos os estados',
    'No recalls found': 'Não foram encontrados seguimentos',
    'There are no recalls for this filter.': 'Não existem seguimentos para este filtro.',
    Update: 'Atualizar',
    'Update recall': 'Atualizar seguimento',
    'Recall history': 'Histórico de seguimentos',
    'Compact history of this patient’s follow-ups.': 'Histórico compacto dos seguimentos deste paciente.',
    Waitlist: 'Lista de espera',
    Reports: 'Relatórios',
    'Operational overview': 'Visão operacional',
    'Review appointment volume by date, doctor, and status. This report contains operational data only.': 'Consulte o volume de consultas por data, médico e estado. Este relatório contém apenas dados operacionais.',
    'Export visible CSV': 'Exportar CSV visível',
    From: 'De',
    To: 'Até',
    Doctor: 'Médico',
    'All doctors': 'Todos os médicos',
    'Agenda for': 'Agenda de',
    'Linked doctor': 'Médico associado',
    'Not linked': 'Não associado',
    'Create a doctor profile before creating a dentist account.': 'Crie primeiro um perfil de médico antes de criar uma conta de médico dentista.',
    'Apply filters': 'Aplicar filtros',
    'Choose a valid inclusive date range.': 'Escolha um intervalo de datas inclusivo válido.',
    'Dates are inclusive. The report is limited to 200 rows.': 'As datas são inclusivas. O relatório está limitado a 200 linhas.',
    'Loading reports': 'A carregar relatórios',
    'Report totals': 'Totais do relatório',
    'Total appointments': 'Total de consultas',
    'Matching the selected filters': 'Correspondentes aos filtros selecionados',
    'Appointments scheduled': 'Consultas marcadas',
    'Appointments completed': 'Consultas concluídas',
    'No-shows': 'Faltas',
    'Appointments marked as no-show': 'Consultas marcadas como falta',
    'Appointment rows': 'Linhas de consultas',
    Date: 'Data',
    Time: 'Hora',
    Duration: 'Duração',
    'Treatment type': 'Tipo de consulta',
    Arrived: 'Chegado',
    Cancelled: 'Cancelada',
    'No-show': 'Falta',
    'No appointments match these filters.': 'Não existem consultas para estes filtros.',
    'Try a wider period or a different status.': 'Experimente um período mais amplo ou outro estado.',
    'Showing the first 200 matching rows.': 'A mostrar as primeiras 200 linhas correspondentes.',
    'Unknown doctor': 'Médico desconhecido',
    'Operational data only': 'Apenas dados operacionais',
    'Operational scheduling': 'Agendamento operacional',
    'Keep patients visible when they are looking for an earlier or future opening.': 'Mantenha visíveis os pacientes que procuram uma vaga mais cedo ou no futuro.',
    'Add to waitlist': 'Adicionar à lista de espera',
    'Keep a short operational request for a future opening.': 'Registe um pedido operacional curto para uma vaga futura.',
    'Schedule appointment': 'Marcar consulta',
    'Dentists can only schedule appointments for themselves.': 'Os médicos dentistas só podem marcar consultas para si próprios.',
    'Select a date': 'Selecione uma data',
    'Previous month': 'Mês anterior',
    'Next month': 'Mês seguinte',
    Clear: 'Limpar',
    'Not set': 'Não definido',
    'Open calendar': 'Abrir calendário',
    'YYYY-MM-DD': 'AAAA-MM-DD',
    'Requested date': 'Data pretendida',
    Priority: 'Prioridade',
    Normal: 'Normal',
    Urgent: 'Urgente',
    'Doctor (optional)': 'Médico (opcional)',
    'Any doctor': 'Qualquer médico',
    'Short notes': 'Notas curtas',
    'Optional operational note': 'Nota operacional opcional',
    'e.g. Earlier appointment': 'por exemplo, consulta mais cedo',
    'Patient and reason are required.': 'Paciente e motivo são obrigatórios.',
    'Waitlist queue': 'Fila da lista de espera',
    'Prioritised requests and their current state.': 'Pedidos prioritários e o seu estado atual.',
    'No requested date': 'Sem data pretendida',
    Waiting: 'Em espera',
    Contacted: 'Contactado',
    Booked: 'Marcado',
    Removed: 'Removido',
    'Waiting and contacted': 'Em espera e contactados',
    'No waitlist entries found': 'Não foram encontrados pedidos na lista de espera',
    'There are no entries for this filter.': 'Não existem pedidos para este filtro.',
    'Update waitlist entry': 'Atualizar pedido da lista de espera',
    'Waitlist history': 'Histórico da lista de espera',
    'Compact history of this patient’s waitlist requests.': 'Histórico compacto dos pedidos deste paciente na lista de espera.',
  },
};

function getStoredLanguage() {
  const stored = window.localStorage.getItem(STORAGE_KEY);
  return LANGUAGE_OPTIONS.some((option) => option.value === stored) ? stored : DEFAULT_LANGUAGE;
}

export default function LanguageProvider({ children }) {
  const { user } = useAuth();
  const [language, setLanguageState] = useState(getStoredLanguage);
  const hasLocalLanguageChange = useRef(false);

  useEffect(() => {
    let isMounted = true;
    hasLocalLanguageChange.current = false;
    if (!user) return undefined;

    apiRequest('/api/settings')
      .then((settings) => {
        if (isMounted && !hasLocalLanguageChange.current && settings?.language) {
          setLanguageState(settings.language);
          window.localStorage.setItem(STORAGE_KEY, settings.language);
        }
      })
      .catch(() => {});

    return () => {
      isMounted = false;
    };
  }, [user]);

  const setLanguage = useCallback((nextLanguage) => {
    const normalized = LANGUAGE_OPTIONS.some((option) => option.value === nextLanguage)
      ? nextLanguage
      : DEFAULT_LANGUAGE;
    hasLocalLanguageChange.current = true;
    setLanguageState(normalized);
    window.localStorage.setItem(STORAGE_KEY, normalized);
  }, []);

  const t = useCallback((value) => translations[language]?.[value] || value, [language]);

  useEffect(() => {
    document.documentElement.lang = language === 'pt-PT' ? 'pt-PT' : 'en';
  }, [language]);

  const value = useMemo(() => ({
    language,
    locale: language === 'pt-PT' ? 'pt-PT' : 'en-GB',
    setLanguage,
    t,
  }), [language, setLanguage, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
