import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { apiRequest } from '../services/api';
import useAuth from './useAuth';
import { LanguageContext } from './language-context';
import { LANGUAGE_OPTIONS } from './languageConstants';

const STORAGE_KEY = 'dentalpro-language';
const DEFAULT_LANGUAGE = 'en';

const translations = {
  'pt-PT': {
    'Clinic workspace': 'Espaço da clínica',
    'Clinical Suite': 'Suite clínica',
    Dashboard: 'Painel',
    Patients: 'Pacientes',
    Agenda: 'Agenda',
    Doctors: 'Médicos',
    Settings: 'Definições',
    'Sign out': 'Terminar sessão',
    'Sign in': 'Iniciar sessão',
    'Signing in…': 'A iniciar sessão…',
    'Sign in to manage the clinic safely.': 'Inicie sessão para gerir a clínica em segurança.',
    Email: 'Email',
    Password: 'Palavra-passe',
    'Loading clinic workspace…': 'A carregar o espaço da clínica…',
    'Clinic setup': 'Configuração da clínica',
    'Configure the operational rules used by the agenda, new appointments, and rescheduling.': 'Configure as regras operacionais usadas pela agenda, pelos novos agendamentos e pelos reagendamentos.',
    'Only administrators can change clinic settings.': 'Apenas os administradores podem alterar as definições da clínica.',
    'Practice schedule': 'Horário da clínica',
    'These hours control every available start time in the booking engine.': 'Este horário controla todas as horas de início disponíveis no sistema de agendamento.',
    'Clinic name': 'Nome da clínica',
    Timezone: 'Fuso horário',
    Language: 'Idioma',
    English: 'Inglês',
    'Portuguese (Portugal)': 'Português (Portugal)',
    Day: 'Dia',
    Open: 'Aberto',
    Hours: 'Horário',
    Break: 'Pausa',
    Monday: 'Segunda-feira',
    Tuesday: 'Terça-feira',
    Wednesday: 'Quarta-feira',
    Thursday: 'Quinta-feira',
    Friday: 'Sexta-feira',
    Saturday: 'Sábado',
    Sunday: 'Domingo',
    to: 'a',
    'Appointment grid is fixed at 30 minutes. The latest valid start is calculated from the closing time and duration.': 'A grelha de agendamento está fixa em intervalos de 30 minutos. A última hora válida é calculada a partir do fecho e da duração.',
    'Save schedule': 'Guardar horário',
    'Closures and holidays': 'Encerramentos e feriados',
    'Block a specific date without changing the weekly schedule.': 'Bloqueie uma data específica sem alterar o horário semanal.',
    'Reason, e.g. Christmas': 'Motivo, por exemplo Natal',
    Add: 'Adicionar',
    'No special closures configured.': 'Não existem encerramentos especiais configurados.',
    'Appointment types': 'Tipos de consulta',
    'Templates set the default duration used by new bookings.': 'Os modelos definem a duração predefinida dos novos agendamentos.',
    'Appointment type': 'Tipo de consulta',
    'Appointment type added.': 'Tipo de consulta adicionado.',
    'Appointment type saved.': 'Tipo de consulta guardado.',
    'Appointment type archived. Existing appointments are unchanged.': 'Tipo de consulta arquivado. As consultas existentes não foram alteradas.',
    'Provider availability': 'Disponibilidade dos médicos',
    'Override the clinic schedule for individual doctors when their working days differ.': 'Sobreponha o horário da clínica para médicos individuais quando os seus dias de trabalho forem diferentes.',
    Works: 'Trabalha',
    min: 'min',
    Remove: 'Remover',
    Archive: 'Arquivar',
    'works on': 'trabalha à',
    'Save provider schedule for': 'Guardar horário de',
    'Configure weekly availability': 'Configurar disponibilidade semanal',
    'Signed-in account': 'Conta com sessão iniciada',
    'Settings are protected by role': 'As definições estão protegidas por função',
    'Slot interval: 30 minutes': 'Intervalo: 30 minutos',
    'Clinic schedule saved. Availability now uses these hours.': 'Horário da clínica guardado. A disponibilidade usa agora este horário.',
    'Closure added. No appointments can be booked on that date.': 'Encerramento adicionado. Não é possível marcar consultas nessa data.',
    'Closure removed.': 'Encerramento removido.',
    'Provider schedule saved.': 'Horário do médico guardado.',
    'Add a doctor first to configure provider availability.': 'Adicione primeiro um médico para configurar a disponibilidade.',
    'Failed to load clinic settings': 'Não foi possível carregar as definições da clínica',
    'Failed to save clinic settings': 'Não foi possível guardar as definições da clínica',
    'New password and confirmation do not match.': 'A nova palavra-passe e a confirmação não coincidem.',
    'Password changed successfully. Other signed-in sessions were signed out.': 'Palavra-passe alterada com sucesso. As outras sessões iniciadas foram terminadas.',
    'Failed to change password': 'Não foi possível alterar a palavra-passe',
    'Failed to add closure': 'Não foi possível adicionar o encerramento',
    'Failed to remove closure': 'Não foi possível remover o encerramento',
    'Failed to add appointment type': 'Não foi possível adicionar o tipo de consulta',
    'Failed to save appointment type': 'Não foi possível guardar o tipo de consulta',
    'Failed to archive appointment type': 'Não foi possível arquivar o tipo de consulta',
    'Failed to save provider schedule': 'Não foi possível guardar o horário do médico',
    'Current password': 'Palavra-passe atual',
    'New password': 'Nova palavra-passe',
    'Confirm new password': 'Confirmar nova palavra-passe',
    'Changing password…': 'A alterar a palavra-passe…',
    'Change password': 'Alterar palavra-passe',
    'Other sessions are revoked after a change': 'As outras sessões são terminadas após a alteração',
    'Loading clinic settings…': 'A carregar as definições da clínica…',
    'Save': 'Guardar',
    'Cancel': 'Cancelar',
    'Close': 'Fechar',
    'Search': 'Pesquisar',
    'Save changes': 'Guardar alterações',
    'No appointments': 'Sem consultas',
    'Upcoming agenda': 'Próximas consultas',
    'Clinic overview': 'Visão geral da clínica',
    'Review patients and upcoming appointments across the clinic.': 'Consulte os pacientes e as próximas consultas da clínica.',
    'Open Patients': 'Abrir pacientes',
    'Patient count': 'Número de pacientes',
    'Current registered patients': 'Pacientes atualmente registados',
    'Next scheduled appointments': 'Próximas consultas marcadas',
    'Unknown patient': 'Paciente desconhecido',
    Consultation: 'Consulta',
    'No upcoming appointments': 'Sem próximas consultas',
    'Future scheduled appointments will appear here.': 'As consultas futuras marcadas aparecerão aqui.',
    'Open agenda': 'Abrir agenda',
    'Add appointment': 'Adicionar consulta',
    'Add doctor': 'Adicionar médico',
    'Add patient': 'Adicionar paciente',
    'Search all patients and work from today\'s active appointment list.': 'Pesquise pacientes e trabalhe a partir da lista de consultas ativas de hoje.',
    'Search all patients by name, phone, email or NIF': 'Pesquisar pacientes por nome, telefone, email ou NIF',
    'Search results': 'Resultados da pesquisa',
    'All existing patients': 'Todos os pacientes existentes',
    result: 'resultado',
    results: 'resultados',
    'No matching patients found': 'Não foram encontrados pacientes correspondentes',
    'Try a different name, phone, email or NIF.': 'Tente outro nome, telefone, email ou NIF.',
    'Open patient': 'Abrir paciente',
    'Patients with appointments today': 'Pacientes com consultas hoje',
    'No patients scheduled for today': 'Não há pacientes marcados para hoje',
    'Today\'s operational patient list will appear here once appointments exist.': 'A lista operacional de pacientes de hoje aparecerá aqui quando existirem consultas.',
    'Full name, phone, email, NIF and nationality are required': 'Nome completo, telefone, email, NIF e nacionalidade são obrigatórios',
    'Portuguese NIF must contain exactly 9 digits': 'O NIF português deve conter exatamente 9 algarismos',
    'Search all doctors and manage clinical staff records.': 'Pesquise médicos e faça a gestão dos registos da equipa clínica.',
    'Search all doctors by name, email, phone or specialty': 'Pesquisar médicos por nome, email, telefone ou especialidade',
    'Secretary workflow': 'Fluxo de trabalho da receção',
    'Review the week, prepare today\'s patients, and manage bookings.': 'Consulte a semana, prepare os pacientes de hoje e faça a gestão das marcações.',
    Week: 'Semana',
    Month: 'Mês',
    Today: 'Hoje',
    'Create Appointment': 'Criar consulta',
    'Reschedule Appointment': 'Reagendar consulta',
    'Save reschedule': 'Guardar reagendamento',
    'Open appointment': 'Abrir consulta',
    'Back to patients': 'Voltar aos pacientes',
    'Completed appointment': 'Consulta concluída',
    'Appointment detail': 'Detalhes da consulta',
    Appointment: 'Consulta',
    'Review the completed visit outcome and recorded notes.': 'Consulte o resultado da visita e as notas registadas.',
    'Review timing, treatment, completion outcome, and reschedule safely when needed.': 'Consulte o horário, tratamento e resultado, e reagende em segurança quando necessário.',
    'Edit appointment': 'Editar consulta',
    Reschedule: 'Reagendar',
    Patient: 'Paciente',
    'Linked patient information': 'Informação do paciente associado',
    'No phone number available': 'Número de telefone indisponível',
    'Open patient record': 'Abrir registo do paciente',
    'Related appointments': 'Consultas relacionadas',
    'Recent appointments for this patient': 'Consultas recentes deste paciente',
    'No other appointments found': 'Não foram encontradas outras consultas',
    'Mark as arrived': 'Marcar como chegado',
    'Mark as no-show': 'Marcar como falta',
    'Conclude appointment': 'Concluir consulta',
    'Workflow actions': 'Ações da consulta',
    'Update attendance, conclude the visit, or move directly into follow-up scheduling.': 'Atualize a presença, conclua a consulta ou avance diretamente para o reagendamento.',
    'Reschedule appointment': 'Reagendar consulta',
    'Conclude Appointment': 'Concluir consulta',
    'This appointment has already been concluded.': 'Esta consulta já foi concluída.',
    'This appointment is closed and cannot be edited or rescheduled': 'Esta consulta está encerrada e não pode ser editada ou reagendada.',
    'Clinical record': 'Registo clínico',
    'Medical history': 'Histórico clínico',
    'Treatment plan': 'Plano de tratamento',
    Odontogram: 'Odontograma',
    'Patient data governance': 'Governação dos dados do paciente',
    'Review consent history and export the structured patient record as JSON.': 'Consulte o histórico de consentimentos e exporte o registo estruturado do paciente em JSON.',
    'Preparing export...': 'A preparar a exportação…',
    'Download JSON export': 'Transferir exportação JSON',
    'Unable to load consent records.': 'Não foi possível carregar os registos de consentimento.',
    'Consent recorded.': 'Consentimento registado.',
    'Unable to record consent.': 'Não foi possível registar o consentimento.',
    'Withdraw this consent?': 'Retirar este consentimento?',
    'Consent withdrawn.': 'Consentimento retirado.',
    'Unable to withdraw consent.': 'Não foi possível retirar o consentimento.',
    'Structured patient record downloaded.': 'Registo estruturado do paciente transferido.',
    'Unable to export the patient record.': 'Não foi possível exportar o registo do paciente.',
    Purpose: 'Finalidade',
    'e.g. Treatment and care': 'por exemplo, Tratamento e cuidados',
    Version: 'Versão',
    'Signature reference': 'Referência da assinatura',
    optional: 'opcional',
    'Saving...': 'A guardar…',
    'Record consent': 'Registar consentimento',
    'Your role can view consent records and export this patient record, but cannot change consent.': 'A sua função pode consultar os registos de consentimento e exportar este registo do paciente, mas não pode alterar o consentimento.',
    'Consent history': 'Histórico de consentimentos',
    'Loading consent records...': 'A carregar os registos de consentimento…',
    'No consent records have been recorded.': 'Ainda não foram registados consentimentos.',
    Withdrawn: 'Retirado',
    Granted: 'Concedido',
    withdrawn: 'retirado',
    Withdraw: 'Retirar',
    'User management': 'Gestão de utilizadores',
    'Create staff accounts and control who can sign in to the clinic.': 'Crie contas da equipa e controle quem pode iniciar sessão na clínica.',
    'Failed to load users': 'Não foi possível carregar os utilizadores',
    'User created successfully.': 'Utilizador criado com sucesso.',
    'Failed to create user': 'Não foi possível criar o utilizador',
    'Failed to update user status': 'Não foi possível atualizar o estado do utilizador',
    'is now': 'está agora',
    Administrator: 'Administrador',
    Receptionist: 'Rececionista',
    Dentist: 'Médico dentista',
    'Display name': 'Nome a apresentar',
    Role: 'Função',
    'Temporary password': 'Palavra-passe temporária',
    'Use at least 12 characters.': 'Utilize pelo menos 12 caracteres.',
    'Saving…': 'A guardar…',
    'Create user': 'Criar utilizador',
    'Loading users…': 'A carregar utilizadores…',
    Name: 'Nome',
    Status: 'Estado',
    Action: 'Ação',
    '(you)': '(você)',
    Active: 'Ativo',
    Inactive: 'Inativo',
    'You cannot deactivate your own account': 'Não pode desativar a sua própria conta',
    'Cannot deactivate': 'Não é possível desativar',
    Deactivate: 'Desativar',
    Activate: 'Ativar',
    'No users found.': 'Não foram encontrados utilizadores.',
    'Your own active account cannot be deactivated here.': 'A sua própria conta ativa não pode ser desativada aqui.',
    Recalls: 'Recalls',
    'Patient follow-up': 'Seguimento de pacientes',
    'Recall queue': 'Fila de recalls',
    'Keep patient follow-ups visible and easy to update.': 'Mantenha os seguimentos dos pacientes visíveis e fáceis de atualizar.',
    'Follow-up dates and their current status.': 'Datas de seguimento e o respetivo estado.',
    'Record a date for the next patient follow-up.': 'Registe uma data para o próximo seguimento do paciente.',
    'Create recall': 'Criar recall',
    'Due date': 'Data prevista',
    Reason: 'Motivo',
    'e.g. Six-month check-up': 'por exemplo, consulta de rotina semestral',
    'Select patient': 'Selecionar paciente',
    'Patient, due date and reason are required.': 'Paciente, data prevista e motivo são obrigatórios.',
    'Filter by status': 'Filtrar por estado',
    Pending: 'Pendentes',
    Due: 'Pendente',
    Scheduled: 'Agendado',
    Completed: 'Concluído',
    Dismissed: 'Dispensado',
    'All statuses': 'Todos os estados',
    'No recalls found': 'Não foram encontrados recalls',
    'There are no recalls for this filter.': 'Não existem recalls para este filtro.',
    Update: 'Atualizar',
    'Update recall': 'Atualizar recall',
    'Recall history': 'Histórico de recalls',
    'Compact history of this patient’s follow-ups.': 'Histórico compacto dos seguimentos deste paciente.',
    Waitlist: 'Lista de espera',
    Reports: 'Relatórios',
    'Operational overview': 'Visão operacional',
    'Review appointment volume by date, doctor, and status. This report contains operational data only.': 'Consulte o volume de consultas por data, médico e estado. Este relatório contém apenas dados operacionais.',
    'Export visible CSV': 'Exportar CSV visível',
    From: 'De',
    To: 'Até',
    Doctor: 'Médico',
    'All doctors': 'Todos os médicos',
    'Apply filters': 'Aplicar filtros',
    'Choose a valid inclusive date range.': 'Escolha um intervalo de datas inclusivo válido.',
    'Dates are inclusive. The report is limited to 200 rows.': 'As datas são inclusivas. O relatório está limitado a 200 linhas.',
    'Loading reports': 'A carregar relatórios',
    'Report totals': 'Totais do relatório',
    'Total appointments': 'Total de consultas',
    'Matching the selected filters': 'Correspondentes aos filtros selecionados',
    'Appointments scheduled': 'Consultas marcadas',
    'Appointments completed': 'Consultas concluídas',
    'No-shows': 'Faltas',
    'Appointments marked as no-show': 'Consultas marcadas como falta',
    'Appointment rows': 'Linhas de consultas',
    Date: 'Data',
    Time: 'Hora',
    Duration: 'Duração',
    'Treatment type': 'Tipo de consulta',
    Arrived: 'Chegado',
    Cancelled: 'Cancelada',
    'No-show': 'Falta',
    'No appointments match these filters.': 'Não existem consultas para estes filtros.',
    'Try a wider period or a different status.': 'Experimente um período mais amplo ou outro estado.',
    'Showing the first 200 matching rows.': 'A mostrar as primeiras 200 linhas correspondentes.',
    'Unknown doctor': 'Médico desconhecido',
    'Operational data only': 'Apenas dados operacionais',
    'Operational scheduling': 'Agendamento operacional',
    'Keep patients visible when they are looking for an earlier or future opening.': 'Mantenha visíveis os pacientes que procuram uma vaga mais cedo ou no futuro.',
    'Add to waitlist': 'Adicionar à lista de espera',
    'Keep a short operational request for a future opening.': 'Registe um pedido operacional curto para uma vaga futura.',
    'Requested date': 'Data pretendida',
    Priority: 'Prioridade',
    Normal: 'Normal',
    Urgent: 'Urgente',
    'Doctor (optional)': 'Médico (opcional)',
    'Any doctor': 'Qualquer médico',
    'Short notes': 'Notas curtas',
    'Optional operational note': 'Nota operacional opcional',
    'e.g. Earlier appointment': 'por exemplo, consulta mais cedo',
    'Patient and reason are required.': 'Paciente e motivo são obrigatórios.',
    'Waitlist queue': 'Fila da lista de espera',
    'Prioritised requests and their current state.': 'Pedidos prioritários e o seu estado atual.',
    'No requested date': 'Sem data pretendida',
    Waiting: 'Em espera',
    Contacted: 'Contactado',
    Booked: 'Marcado',
    Removed: 'Removido',
    'Waiting and contacted': 'Em espera e contactados',
    'No waitlist entries found': 'Não foram encontrados pedidos na lista de espera',
    'There are no entries for this filter.': 'Não existem pedidos para este filtro.',
    'Update waitlist entry': 'Atualizar pedido da lista de espera',
    'Waitlist history': 'Histórico da lista de espera',
    'Compact history of this patient’s waitlist requests.': 'Histórico compacto dos pedidos deste paciente na lista de espera.',
  },
};

function getStoredLanguage() {
  const stored = window.localStorage.getItem(STORAGE_KEY);
  return LANGUAGE_OPTIONS.some((option) => option.value === stored) ? stored : DEFAULT_LANGUAGE;
}

export default function LanguageProvider({ children }) {
  const { user } = useAuth();
  const [language, setLanguageState] = useState(getStoredLanguage);
  const hasLocalLanguageChange = useRef(false);

  useEffect(() => {
    let isMounted = true;
    hasLocalLanguageChange.current = false;
    if (!user) return undefined;

    apiRequest('/api/settings')
      .then((settings) => {
        if (isMounted && !hasLocalLanguageChange.current && settings?.language) {
          setLanguageState(settings.language);
          window.localStorage.setItem(STORAGE_KEY, settings.language);
        }
      })
      .catch(() => {});

    return () => {
      isMounted = false;
    };
  }, [user]);

  const setLanguage = useCallback((nextLanguage) => {
    const normalized = LANGUAGE_OPTIONS.some((option) => option.value === nextLanguage)
      ? nextLanguage
      : DEFAULT_LANGUAGE;
    hasLocalLanguageChange.current = true;
    setLanguageState(normalized);
    window.localStorage.setItem(STORAGE_KEY, normalized);
  }, []);

  const t = useCallback((value) => translations[language]?.[value] || value, [language]);

  useEffect(() => {
    document.documentElement.lang = language === 'pt-PT' ? 'pt-PT' : 'en';
  }, [language]);

  const value = useMemo(() => ({
    language,
    locale: language === 'pt-PT' ? 'pt-PT' : 'en-GB',
    setLanguage,
    t,
  }), [language, setLanguage, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
